language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
 - ./tests/install-php-extension.sh
 - composer self-update
 - composer install --dev --no-interaction

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v